from typing import List,TypedDict

class GraphState(TypedDict):
    """
    Represents the state of the graph.

    Attributes :
        question : question asked by the user.
        generation : answer generated by the LLM.
        web_search : whether web search was used to answer the question.
        documents : documents retrieved from the vectorstore.
    """

    question: str
    generation: str
    web_search: bool
    documents: List[str]